// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgNvjpo7jb9G0Os4DTlRqWPlyfaJoKAwI',
    appId: '1:213024882901:web:ddce18c9dbeb636a55a25c',
    messagingSenderId: '213024882901',
    projectId: 'padigos-chat-app',
    authDomain: 'padigos-chat-app.firebaseapp.com',
    storageBucket: 'padigos-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7eQUm0CRaLQNtKGYXaWC2dHH_-J8yRhE',
    appId: '1:213024882901:android:21b27226f7aeab3955a25c',
    messagingSenderId: '213024882901',
    projectId: 'padigos-chat-app',
    storageBucket: 'padigos-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjq1QIxv1eIyExgTppfFZMwyCPCgkJHQ',
    appId: '1:213024882901:ios:b7a875f8d2f1167855a25c',
    messagingSenderId: '213024882901',
    projectId: 'padigos-chat-app',
    storageBucket: 'padigos-chat-app.appspot.com',
    iosClientId:
        '213024882901-4t28bm0cp3iho6jjep0q72g1926pinmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
